baseURL = "https://brighamcampbell.com/"
languageCode = "en-us"
title = "Brigham Campbell's Notes"
disableKinds = ['taxonomy', 'term', 'section']
enableEmoji = true
disableHugoGeneratorInject = true

[params]
    email = "me@brighamcampbell.com"
    imageQuality = 75
    responsiveImageWidths = [360, 420, 560, 700]
    responsiveImageSizes = "(max-width: 700px) 100vw, 700px"

[minify]
    minifyOutput = true
