baseURL = "https://brighamcampbell.com/"
languageCode = "en-us"
title = "Brigham Campbell's Notes"
disableKinds = ['taxonomy', 'term', 'section']
enableEmoji = true

[params]
    email = "me@brighamcampbell.com"
    imageQuality = 75
    responsiveImageWidths = [160, 320, 480, 700, 980]
    responsiveImageSizes = "(max-width: 700px) 100vw, 700px"

[minify]
    minifyOutput = true